#!/usr/bin/env python3
"""
=============================================================================
                           FrustraMotion Parser - Contacts
=============================================================================

This script processes directories containing contact/interaction
frustration data generated by FrustratometeR. It consolidates multiple 
simulation frames into Tidy DataFrames, ideal for tracking dynamic 
interactions, water-mediated bridges, and structural networks over time.

Output format:
Frame | Chain1 | Res1 | Chain2 | Res2 | ResID1 | ResID2 | Welltype | FrstIndex
----------------------------------------------------------------------------
  0   |   A    |  W45 |   A    |  R70 |  A:W45 |  A:R70 |  short   |   0.77
  10  |   A    |  W45 |   B    |  M1  |  A:W45 |  B:M1  |  water   |  -1.20

Usage example:
    python parser_contact.py -i ./raw_data -o ./parsed_contacts -p TmEnc -t configurational -c A B C
=============================================================================
"""

import os
import sys
import re
import argparse
import pandas as pd
import numpy as np


def parse_arguments():
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(
        description='Parse multiple FrustratometeR .done directories into contact time-series DataFrames.'
    )
    
    parser.add_argument(
        '-i', '--input_dir', 
        type=str, 
        required=True,
        help='Input directory containing the .done folders.'
    )

    parser.add_argument(
        '-t', '--type', 
        type=str, 
        default='configurational',
        choices=['configurational', 'mutational'],
        help='Type of contact data to parse: "configurational" or "mutational" (Default: configurational).'
    )
    
    parser.add_argument(
        '-o', '--out_dir', 
        type=str, 
        default='./parsed_contacts',
        help='Output directory where the parsed CSV files will be saved. (Default: ./parsed_contacts)'
    )
    
    parser.add_argument(
        '-p', '--protein_name', 
        type=str, 
        default='Protein',
        help='Name of the protein to be used as a prefix for output files. (Default: Protein)'
    )
    
    parser.add_argument(
        '-c', '--chains', 
        nargs='+', 
        default=None,
        help='List of chains to process (e.g., -c A B C). If omitted, processes all.'
    )

    args = parser.parse_args()

    if not os.path.isdir(args.input_dir):
        print(f"[!] Error: The input directory '{args.input_dir}' does not exist.")
        sys.exit(1)

    return args.input_dir, args.out_dir, args.protein_name, args.chains, args.type


def extract_frame_number(dirname):
    """Extract the frame number from the directory name using Regex."""
    base_name = dirname.replace('.done', '')
    numbers = re.findall(r'\d+', base_name)
    
    if numbers:
        return int(numbers[-1])
    else:
        return float('inf')


def parse_contact_files(input_dir, chains_to_process=None, contact_type='configurational'):
    """
    Scans the input directory, locates specific frustration files based on contact_type,
    and consolidates them into a single Tidy DataFrame.
    """
    print(f"[*] Scanning directories for '{contact_type}' frustration data...")
    
    file_frame_pairs = []
    
    # 1. Collect all valid files matching the requested type
    for dirname in os.listdir(input_dir):
        if not dirname.endswith('.done'):
            continue
            
        full_path = os.path.join(input_dir, dirname)
        frustration_data_path = os.path.join(full_path, "FrustrationData")
        
        if os.path.isdir(frustration_data_path):
            for file in os.listdir(frustration_data_path):
                if file.endswith(contact_type):
                    contact_file_path = os.path.join(frustration_data_path, file)
                    frame_num = extract_frame_number(dirname)
                    file_frame_pairs.append((contact_file_path, frame_num))

    if not file_frame_pairs:
        print(f"[!] Error: No valid '{contact_type}' files found in {input_dir}.")
        sys.exit(1)

    print(f"[*] Found {len(file_frame_pairs)} valid frames. Processing...")
    
    all_dataframes = []

    # 2. Process each file
    for file_path, frame_num in file_frame_pairs:
        try:
            df = pd.read_csv(
                file_path,
                sep=r'\s+',
                header=0,
                names=[
                    'Res1', 'Res2', 'ChainRes1', 'ChainRes2',
                    'DensityRes1', 'DensityRes2', 'AA1', 'AA2',
                    'NativeEnergy', 'DecoyEnergy', 'SDEnergy',
                    'FrstIndex', 'Welltype', 'FrstState'
                ],
                usecols=[
                    'Res1', 'Res2', 'ChainRes1', 'ChainRes2',
                    'AA1', 'AA2', 'FrstIndex', 'Welltype', 'FrstState'
                ],
                # Leer como string al principio para evitar problemas si hay letras en el PDB (ej. '12A')
                dtype={'Res1': str, 'Res2': str, 'ChainRes1': str, 'ChainRes2': str, 'AA1': str, 'AA2': str}
            )
            
            df['Frame'] = frame_num

            # Filter by chains if specified
            if chains_to_process:
                df = df[df['ChainRes1'].isin(chains_to_process) | df['ChainRes2'].isin(chains_to_process)]
                if df.empty:
                    continue
            
            # 1. Convertimos a numérico (los que no se puedan, quedan como NaN)
            df['Res1_num'] = pd.to_numeric(df['Res1'], errors='coerce')
            df['Res2_num'] = pd.to_numeric(df['Res2'], errors='coerce')
            
            # 2. Rellenamos los NaN (por si había un residuo raro como '45A') con el string original
            # y eliminamos el '.0' si es que se agregó
            df['Res1_clean'] = df['Res1_num'].fillna(df['Res1']).astype(str).str.replace(r'\.0$', '', regex=True)
            df['Res2_clean'] = df['Res2_num'].fillna(df['Res2']).astype(str).str.replace(r'\.0$', '', regex=True)

            # Create standard Identifiers (e.g., A:W45) usando el número limpio exacto del archivo
            df['ResID1'] = df['ChainRes1'] + ':' + df['AA1'] + df['Res1_clean']
            df['ResID2'] = df['ChainRes2'] + ':' + df['AA2'] + df['Res2_clean']

            # Select and reorder columns for final Tidy format
            df_clean = df[[
                'Frame', 'ChainRes1', 'ChainRes2', 'ResID1', 'ResID2', 
                'Welltype', 'FrstState', 'FrstIndex'
            ]]
            
            all_dataframes.append(df_clean)
            
        except Exception as e:
            print(f"[!] Warning: Error reading {file_path}. ({e})")
            continue

    if not all_dataframes:
         print("[!] Error: No data could be extracted based on the provided filters.")
         sys.exit(1)

    # 3. Concatenate everything
    print("[*] Assembling Tidy Contact DataFrames...")
    master_df = pd.concat(all_dataframes, ignore_index=True)
    
    # Sort chronologically
    master_df = master_df.sort_values(by=['Frame', 'ChainRes1', 'ChainRes2']).reset_index(drop=True)

    return master_df


def get_compact_chain_id(chain_id):
    """
    Genera un ID de cadena compacto.
    Si es mayúscula o número, lo deja igual.
    Si es minúscula, le antepone un guion bajo (ej. 't' -> '_t').
    """
    chain_str = str(chain_id)[0]
    
    if chain_str.islower():
        return f"_{chain_str}"
    else:
        return chain_str


def save_contact_data(master_df, out_dir, protein_name, contact_type):
    """
    Saves the processed Contact DataFrames. 
    It splits the master DataFrame into individual files for every unique pair 
    of interacting chains, using a compact naming convention.
    """
    os.makedirs(out_dir, exist_ok=True)
    
    groups = master_df.groupby(['ChainRes1', 'ChainRes2'])
    
    print(f"[*] Saving specific contact files by chain pairs...")
    
    saved_count = 0
    for (chain1, chain2), group in groups:
        # Usamos nuestra función de IDs compactos
        compact_c1 = get_compact_chain_id(chain1)
        compact_c2 = get_compact_chain_id(chain2)
        
        if chain1 == chain2:
            interaction_type = "intra"
            filename = f"{protein_name}_{contact_type}_chain_{compact_c1}_{interaction_type}_contacts.csv"
        else:
            interaction_type = "inter"
            # Ordenamos para evitar tener A_vs_B y B_vs_A
            chains_sorted = sorted([compact_c1, compact_c2])
            filename = f"{protein_name}_{contact_type}_{chains_sorted[0]}_vs_{chains_sorted[1]}_{interaction_type}_contacts.csv"
        
        output_path = os.path.join(out_dir, filename)
        
        if os.path.exists(output_path):
             existing_df = pd.read_csv(output_path)
             combined = pd.concat([existing_df, group]).drop_duplicates()
             combined.to_csv(output_path, index=False)
        else:
             group.to_csv(output_path, index=False)
             
        saved_count += 1
        print(f"   -> Saved: {filename} (Shape: {group.shape})")
        
    print(f"[*] Successfully saved {saved_count} chain-pair files.")


def main():
    # 1. Parse arguments
    input_dir, out_dir, protein_name, chains, contact_type = parse_arguments()
    
    print("\n" + "="*50)
    print(" FrustraMotion Parser - Contacts")
    print("="*50)
    print(f" Input Directory : {input_dir}")
    print(f" Output Directory: {out_dir}")
    print(f" Protein Prefix  : {protein_name}")
    print(f" Contact Type    : {contact_type}")
    if chains:
        print(f" Filter Chains   : {', '.join(chains)}")
    print("="*50 + "\n")

    # 2. Process Data
    contact_data = parse_contact_files(input_dir, chains, contact_type)

    # 3. Save Data
    print("\n[*] Saving results...")
    save_contact_data(contact_data, out_dir, protein_name, contact_type)
    
    print("\n[*] Contact Parsing complete!\n")


if __name__ == "__main__":
    main()