#!/usr/bin/env python3
"""
=============================================================================
                             FrustraMotion Parser
=============================================================================

This script processes directories containing single-residue frustration data 
generated by FrustratometeR. It consolidates multiple simulation frames into 
Tidy DataFrames, optimizing the data for time-series analysis, 
data visualization (e.g., Seaborn), and machine learning applications.

Output format per chain:
Chain | Residue | Frame | FrstIndex
-----------------------------------
  A   |   W45   |   0   |   0.77
  A   |   W45   |   10  |   0.65
  A   |   R70   |   0   |  -1.20

Usage example:
    python parser.py -i ./raw_data -o ./parsed_data -p TmEnc
=============================================================================
"""

import os
import sys
import re
import argparse
import pandas as pd
import numpy as np


def parse_arguments():
    """
    Parse command line arguments.
    """
    parser = argparse.ArgumentParser(
        description='Parse multiple FrustratometeR .done directories into time-series DataFrames.'
    )
    
    parser.add_argument(
        '-i', '--input_dir', 
        type=str, 
        required=True,
        help='Input directory containing the .done folders.'
    )
    
    parser.add_argument(
        '-o', '--out_dir', 
        type=str, 
        default='./parsed_data',
        help='Output directory where the parsed CSV files will be saved. (Default: ./parsed_data)'
    )
    
    parser.add_argument(
        '-p', '--protein_name', 
        type=str, 
        default='Protein',
        help='Name of the protein to be used as a prefix for output files. (Default: Protein)'
    )

    args = parser.parse_args()

    # Verify input directory
    if not os.path.isdir(args.input_dir):
        print(f"[!] Error: The input directory '{args.input_dir}' does not exist.")
        sys.exit(1)

    return args.input_dir, args.out_dir, args.protein_name


def extract_frame_number(dirname):
    """
    Extract the frame number from the directory name using Regex.
    Looks for the last sequence of digits before '.done' or at the end of the string.
    """
    # Remove .done if present
    base_name = dirname.replace('.done', '')
    
    # Find all numbers in the string
    numbers = re.findall(r'\d+', base_name)
    
    if numbers:
        # Assume the last number in the directory name is the frame
        return int(numbers[-1])
    else:
        return float('inf')


def parse_frustration_files(input_dir):
    """
    Scans the input directory, locates 'singleresidue' files,
    and consolidates them into a Tidy DataFrame (Long Format).
    """
    print("[*] Scanning directories for frustration data...")
    
    file_frame_pairs = []
    
    # 1. Collect all valid singleresidue files
    for dirname in os.listdir(input_dir):
        if not dirname.endswith('.done'):
            continue
            
        full_path = os.path.join(input_dir, dirname)
        frustration_data_path = os.path.join(full_path, "FrustrationData")
        
        if os.path.isdir(frustration_data_path):
            for file in os.listdir(frustration_data_path):
                if file.endswith("singleresidue"):
                    single_res_path = os.path.join(frustration_data_path, file)
                    frame_num = extract_frame_number(dirname)
                    file_frame_pairs.append((single_res_path, frame_num))

    if not file_frame_pairs:
        print("[!] Error: No valid files found.")
        sys.exit(1)

    print(f"[*] Found {len(file_frame_pairs)} valid frames. Processing...")
    
    all_dataframes = []

    # 2. Process each file and stack them vertically
    for file_path, frame_num in file_frame_pairs:
        try:
            df_file = pd.read_csv(
                file_path,
                sep=r'\s+', 
                header=0,
                names=[
                    'Res', 'Chain', 'DensityRes', 'AA',
                    'NativeEnergy', 'DecoyEnergy', 'SDEnergy', 'FrstIndex'
                ],
                dtype={'Res': str, 'Chain': str, 'AA': str}
            )
            
            # Get residue num and label
            df_file['Res_num'] = pd.to_numeric(df_file['Res'], errors='coerce')
            df_file['Res_clean'] = df_file['Res_num'].fillna(df_file['Res']).astype(str).str.replace(r'\.0$', '', regex=True)
            
            # Create res label
            df_file['Residue'] = df_file['AA'] + df_file['Res_clean']
            
            # Add frame column
            df_file['Frame'] = frame_num
            
            df_clean = df_file[['Chain', 'Residue', 'Res_num', 'Frame', 'FrstIndex']]
            all_dataframes.append(df_clean)
            
        except Exception as e:
            print(f"[!] Warning: Error reading {file_path}. ({e})")
            continue

    # 3. Concatenate
    print("[*] Assembling Tidy DataFrames...")
    master_df = pd.concat(all_dataframes, ignore_index=True)
    
    # 4. Sort
    result_dfs = {}
    for chain_id, group in master_df.groupby('Chain'):
        sorted_group = group.sort_values(by=['Frame', 'Res_num']).reset_index(drop=True)
        final_df = sorted_group.drop(columns=['Res_num'])
        
        result_dfs[chain_id] = final_df

    return result_dfs


def get_compact_chain_id(chain_id):
    """
    Creates a Chain ID for the file name.
    In upper case or numbers, it remains the same ID.
    In lower case, it adds an underscore before the letter: 't' -> '_t'
    """
    chain_str = str(chain_id)[0]
    
    if chain_str.islower():
        return f"_{chain_str}"
    else:
        return chain_str


def save_dataframes(dataframes_dict, out_dir, protein_name):
    """
    Saves the processed DataFrames into the target directory.
    """
    os.makedirs(out_dir, exist_ok=True)

    for chain_id, df in dataframes_dict.items():
        # Usar la nueva nomenclatura compacta
        compact_chain_id = get_compact_chain_id(chain_id)
        filename = f"{protein_name}_chain_{compact_chain_id}.csv"
        
        output_path = os.path.join(out_dir, filename)
        df.to_csv(output_path, index=False)
        print(f" -> Saved: {output_path} (Shape: {df.shape})")


def main():
    # 1. Parse arguments
    input_dir, out_dir, protein_name = parse_arguments()
    
    print("\n" + "="*50)
    print(" FrustraMotion Parser - Single Residue")
    print("="*50)
    print(f" Input Directory : {input_dir}")
    print(f" Output Directory: {out_dir}")
    print(f" Protein Prefix  : {protein_name}\n")

    # 2. Extract and Process Data
    result_dfs = parse_frustration_files(input_dir)

    # 3. Save Data
    print("\n[*] Saving results...")
    save_dataframes(result_dfs, out_dir, protein_name)
    
    print("\n[*] Parsing complete!\n")


if __name__ == "__main__":
    main()