[workspace]
channels = ["conda-forge"]
name = "cluster_env"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"
pandas = ">=2.3.2,<3"
numpy = ">=2.3.2,<3"
networkx = ">=3.5,<4"
igraph = ">=0.10.16,<0.11"
seaborn = ">=0.13.2,<0.14"
matplotlib = ">=3.10.5,<4"
scikit-learn = ">=1.7.1,<2"
scipy = ">=1.16.1,<2"
python-igraph = ">=0.11.9,<0.12"
leidenalg = ">=0.10.2,<0.11"
