import pandas as pd
import numpy as np
from frustramotion.analysis.base import BaseAnalyzer

class ContactNetworkAnalyzer(BaseAnalyzer):
    """
    Analytical engine for dynamic protein contact networks (edges/pairs).
    Assumes a Tidy DataFrame generated by FrustraMotion's contact parser.
    """
    
    def _validate_columns(self):
        super()._validate_columns()
        
        required_cols = ['ResID1', 'ResID2', 'Welltype', 'FrstState']
        if not all(col in self.df.columns for col in required_cols):
            raise ValueError(f"[!] Error: Contact data must contain the following columns: {required_cols}")
            
        # Build the 'PairID' robustly (A_B is the same as B_A)
        self.df['PairID'] = np.where(
            self.df['ResID1'] < self.df['ResID2'],
            self.df['ResID1'] + '_' + self.df['ResID2'],
            self.df['ResID2'] + '_' + self.df['ResID1']
        )

    def get_contact_persistence(self, min_frequency=0.1):
        counts = self.df.groupby('PairID').size()
        persistence = counts / self.total_frames
        
        valid_pairs = persistence[persistence >= min_frequency]
        
        stats = self.df[self.df['PairID'].isin(valid_pairs.index)].groupby('PairID').agg(
            Mean_FrstIndex=('FrstIndex', 'mean'),
            Predominant_Welltype=('Welltype', lambda x: x.mode()[0]),
            Freq=('FrstIndex', 'count')
        )
        stats['Persistence'] = stats['Freq'] / self.total_frames
        stats = stats.drop(columns=['Freq'])
        
        return stats.sort_values(by='Persistence', ascending=False)

    def get_frustration_hot_edges(self, top_n=10):
        stats = self.get_contact_persistence(min_frequency=0.2)
        hot_edges = stats.sort_values(by='Mean_FrstIndex', ascending=True).head(top_n)
        return hot_edges

    def get_frustration_hubs(self, top_n=5):
        highly_frustrated = self.df[self.df['FrstState'] == 'highly']
        
        counts1 = highly_frustrated['ResID1'].value_counts()
        counts2 = highly_frustrated['ResID2'].value_counts()
        
        hubs = counts1.add(counts2, fill_value=0).sort_values(ascending=False)
        
        hubs = hubs / self.total_frames
        hubs.name = 'Avg_Highly_Frustrated_Contacts_Per_Frame'
        
        return pd.DataFrame(hubs).head(top_n)