import pandas as pd
import numpy as np

class ContactNetworkAnalyzer:
    """
    Analytical engine for dynamic protein contact networks (edges/pairs).
    Assumes a Tidy DataFrame generated by FrustraMotion's contact parser.
    """
    def __init__(self, df):
        self.df = df.copy()

        self.df['PairID'] = self.df.apply(
            lambda x: f"{min(x['ResID1'], x['ResID2'])}_{max(x['ResID1'], x['ResID2'])}", axis=1
        )

    def get_contact_persistence(self, min_frequency=0.1):
        """
        Calculates the percentage of frames where a specific pair is in contact.
        Filters out highly transient noise (< min_frequency).
        """
        total_frames = self.df['Frame'].nunique()
        counts = self.df.groupby('PairID').size()
        persistence = counts / total_frames
        
        valid_pairs = persistence[persistence >= min_frequency]
        
        stats = self.df[self.df['PairID'].isin(valid_pairs.index)].groupby('PairID').agg(
            Mean_FrstIndex=('FrstIndex', 'mean'),
            Predominant_Welltype=('Welltype', lambda x: x.mode()[0]),
            Freq=('FrstIndex', 'count')
        )
        stats['Persistence'] = stats['Freq'] / total_frames
        stats = stats.drop(columns=['Freq'])
        
        return stats.sort_values(by='Persistence', ascending=False)

    def get_frustration_hot_edges(self, top_n=10):
        """
        Identifies the most persistently stressed connections (Hot Edges).
        Focuses on pairs with high persistence AND high frustration (negative FrstIndex).
        """
        stats = self.get_contact_persistence(min_frequency=0.2)
        hot_edges = stats.sort_values(by='Mean_FrstIndex', ascending=True).head(top_n)
        return hot_edges

    def get_frustration_hubs(self, top_n=5):
        """
        Identifies 'Hub' residues that accumulate the highest number of 
        highly frustrated contacts simultaneously.
        """
        highly_frustrated = self.df[self.df['FrstState'] == 'highly']
        
        counts1 = highly_frustrated['ResID1'].value_counts()
        counts2 = highly_frustrated['ResID2'].value_counts()
        
        hubs = counts1.add(counts2, fill_value=0).sort_values(ascending=False)
        
        total_frames = self.df['Frame'].nunique()
        hubs = hubs / total_frames
        hubs.name = 'Avg_Highly_Frustrated_Contacts_Per_Frame'
        
        return pd.DataFrame(hubs).head(top_n)